# Generated by Django 4.1.3 on 2022-12-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recursos_alter_funcionario_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='horas',
            field=models.DateTimeField(auto_now=True, verbose_name='Horas'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='horas',
            field=models.DateTimeField(auto_now=True, verbose_name='Horas'),
        ),
        migrations.AddField(
            model_name='recursos',
            name='horas',
            field=models.DateTimeField(auto_now=True, verbose_name='Horas'),
        ),
        migrations.AddField(
            model_name='servico',
            name='horas',
            field=models.DateTimeField(auto_now=True, verbose_name='Horas'),
        ),
    ]
