# Generated by Django 4.1.3 on 2022-12-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_recursos_icone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recursos2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('descricao', models.TextField(max_length=200, verbose_name='descrição')),
                ('icone', models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-laptop-phone', 'Laptop'), ('lni-leaf', 'Folha'), ('lni-layers', 'Camadas'), ('lni-mobile', 'Modile'), ('lni-rocket', 'Foguete')], max_length=16, verbose_name='icone')),
            ],
            options={
                'verbose_name': 'Recurso2',
                'verbose_name_plural': 'Recursos2',
            },
        ),
        migrations.RenameModel(
            old_name='Recursos',
            new_name='Recursos1',
        ),
        migrations.AlterModelOptions(
            name='recursos1',
            options={'verbose_name': 'Recurso1', 'verbose_name_plural': 'Recursos1'},
        ),
    ]
