# Generated by Django 4.1.3 on 2022-12-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_recursos2_rename_recursos_recursos1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recursos2',
            new_name='Recursos',
        ),
        migrations.DeleteModel(
            name='Recursos1',
        ),
        migrations.AlterModelOptions(
            name='recursos',
            options={'verbose_name': 'Recurso', 'verbose_name_plural': 'Recursos'},
        ),
    ]
